steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/oak-hims-staging:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/oak-hims-staging:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # 2. Push image versi commit
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-commit-image'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/oak-hims-staging:$COMMIT_SHA'

  # 3. Push image latest
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest-image'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/oak-hims-staging:latest'

  # 4. Deploy image ke Cloud Run staging
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'oak-hims-staging'
      - '--image=asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/oak-hims-staging:$COMMIT_SHA'
      - '--region=asia-southeast2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--update-env-vars=NODE_ENV=production'

options:
  logging: CLOUD_LOGGING_ONLY
